# meant to be used locally with docker-compose
#NOTE: do not run docker-compose separately when running app with this profile. kill the containers if they are running

# if you run the app with this `docker` spring profile, `all` docker-compose profile will be selected
# which will initialize MySQL. Also the jdbc url will be automatically created based on the docker-compose.yml file
spring:
    docker:
        compose:
            profiles:
                active:
                    - mysql
                    - mailHog

spring.jpa.hibernate.ddl-auto: update


